language: node_js
node_js: 8.11.1
script:
  - npm install
  - npm run build
  - npm run unzip-aws-artifacts
  - git describe
before_deploy:
  - pip install --user --upgrade awscli
deploy:
  - provider: releases
    api_key:
      secure: 6d3xrjPgKC5hGq1ds2wvmWWmg+VoPdOcFRZy11ToEom36YMRIClenqcywJi4O7DgF4bJLTRMNjCsppQAupTybFQiiWu/SITHerJbeoH1My3zHZFb8KoglQNPdmpT/Mo7aAWwxeo+4rUw5ehOeGdUVMxneh1E4XCBYMcHWoGQlPLsLLaVN50vCWZB9aCDeQbfHMF/FZ0SuHpsWC1JB7GlwO64x0wMsoFkNfi9+Kd1tpS5rjiVuX4pqB7lDkGeujaBxfozPK+TGn3b+PK/asqFUltpw4VQY9gUxySzSiWK4GsjopoTHdlrCQ32kq47hKESpLKWuDrI+uN6aqK9cuWlPGEbTIcn1C5XtGiOVF76PUXStmoMYUnoZzfX9kzcXY0CBLZ55L5BJieykzSJhmjYIDiWL0+rBpLgc6tuUjoXsvm4NxWHhoyrCwSQ77I57Xrzr0P2BIFM3gN55qyLU8I/8TcQ7hLCfZ5HHnqt8YDFY3xHxPKJKyDe9u+4PdfTc2i+GUDp+KuXTyX/ZhNaiRTfff231pR+8Y+dUPQIUSzVkoLezV3zCxCStKgkCyDED1hAK4ZTf4CTERCrFfTJP9bg6aVCuRO/XzeP9NyYDzlBJQyChvJUh3kDNlh7cEfXqLFznxaQBwlTmsFXixNdXYh04i+9IOW16EwlJHTpUocPBDg=
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      repo: fortinet/fortigate-autoscale-aws-tgw
      tags: true
      branch: main
  - provider: script
    script: ~/.local/bin/aws s3 sync distAWS s3://fortinet-github-aws-release-artifacts/fortigate-autoscale-aws-tgw/$TRAVIS_BRANCH --region=us-west-2 --delete --acl=public-read
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != dependabot"
env:
  global:
    - secure: q/piD1rwImklg8ZePU+ZK3VTi6+XmnneJ5Q2AROeXAONMSnoy3TLv4pefxeCEOprzay87NIP1nM2RYuAz+1+ckvAL6H0JYHMPMISdACYpF+2Z91OojYHI/tTsT6URUPJ6t0+23uORcWae+Uj9EnhOKUP6yq+mBoiMncpWteIfkJJy4WYJP1bq2TMpESmfbuJvUBzL4fs/5TvR45MzCaxWGEBiCKmzjSsQUs9nhM23PiuBGimk5FqxXlmA9P0Terv1iQsHBIBePkdpUxsYlrvg7NI8o7E1QFFEqmMhc66V5jXHUO5/zp6jd+94BtzZLuShUIof5JD83o1goG08yZkhx/Y8wWFQQ82PpEMIebViFW2Aecqjm9INKCNPsGfddtZxI8tbonCEXLp6Xx6c4RvVde9tbtEtNJwEC04ehxzU3J3fZbP++1wqrseOLROeOwd7C3iGsl6F/+xJ85EytFNFvtv7m7Azy1WrLTBLJzMJylXijRSBWUFqZ3ZBQxa1FUq04FpOWCpQ5ZgvZKiXPeSANDnzAVfuj8Vn14+Vw/sAF9uyxyDsVZdCxVWJWSUBWN07Qd6yZ9PlnHRzpwjJkgbz6EJPwIx4pqOFBQuF5swQlfY/LzxCanbMGNs8sZ1aYbsh8rv1V0ZSLOcer6JmVaNmHGPhWGOfuGalkpU+5Hq7zA=
    - secure: zjuLgitNaFxBcfxv441u343/EgBKHsPPR6TRe7eT3rP+2DP0FnKynJDxpuWEGwCJNk/jgqjmK+fKJ2xYxrRFYNRKVOvgeIsC/oYLy7td9oALQ4cdhClgNTx4BJf6Vu0aRUJyjiUQpRIChbH/HzBjGTdq6ar0E7eqlynThC2aRbBosdrYb5ERGSjkW7nW9GHrOwOMrGZZYfwCMF3fqcmvwVm+kxw/K4YAxC1jbU/gaGzSR130stwBY4p1NswGAOTy8zkDFHtuLKVpcwgICx4bUXqFaJ1xBS0lSaa8IsjS4VRsFxTdDCs4TPY1IRqB3v/qM/nKImQXAoGhccOUJYcMPHBETiqxkV2tr8Pwvqm/4pAMmsZ0e2hu9hqxDTYA3IRqBieOiPyyuXlRWqGv35s+QhB0wL8O8vvpD2jl3zhxMaK/KyFCdFHqK9xXpLWPFGKHhMqWIysgmiVqheyM+RP0tIo1wsGHlEhVmagLCDCCCPfeUUE+jdAGWPU4BnQcNx+sAUokRE7wHNT+OdyTW5Fsm6pgG+xk6q7Van4oZVIzBjaq4rO43eb4A03tHewVUr98Wd7Irr0Kc5LRo+ok6eCqpSl264EC4VEcUYyUMfLxdzrmW7zG+/H6kahjqYvESIMlgimRg1BohuHFZQ9YJBDLHVu7v34azS+31wr68USXACs=
